import React, { useEffect, useState } from "react";
import { useParams } from "react-router-dom";
import jsPDF from "jspdf";
import autoTable from "jspdf-autotable";   // ✅ FIX

function ScanReport() {

  const { id } = useParams();

  const [scanVulns, setScanVulns] = useState([]);
  const [summary, setSummary] = useState({
    critical: 0,
    high: 0,
    medium: 0,
    low: 0
  });

  const [displayedLogs, setDisplayedLogs] = useState([]);
  const [exploits, setExploits] = useState([]);

  // ---------------- FETCH ----------------
  useEffect(() => {
    fetchVulns();
    fetchLogs();
    fetchExploits();
  }, []);

  const fetchVulns = async () => {
    const res = await fetch(`http://localhost:8000/vulnerabilities/scan/${id}`);
    const data = await res.json();

    setScanVulns(data);

    let critical=0, high=0, medium=0, low=0;

    data.forEach(v=>{
      if(v.severity==="Critical") critical++;
      else if(v.severity==="High") high++;
      else if(v.severity==="Medium") medium++;
      else low++;
    });

    setSummary({critical, high, medium, low});
  };

  const fetchLogs = async () => {
    try{
      const res = await fetch(`http://localhost:8000/logs/${id}`);
      const data = await res.json();
      setDisplayedLogs(data.map(l=>l.message));
    }catch{
      setDisplayedLogs([]);
    }
  };

  const fetchExploits = async () => {
    const res = await fetch(`http://localhost:8000/ai/exploit/${id}`);
    const data = await res.json();
    setExploits(data);
  };

  // ---------------- PDF (🔥 PRO VERSION) ----------------
  const exportPDF = () => {

    const doc = new jsPDF();

    // HEADER
    doc.setFillColor(30, 41, 59);
    doc.rect(0, 0, 210, 30, "F");

    doc.setTextColor(255,255,255);
    doc.setFontSize(18);
    doc.text("AutoVAPT Security Report", 14, 18);

    doc.setTextColor(0,0,0);

    doc.setFontSize(11);
    doc.text(`Scan ID: ${id}`, 14, 40);
    doc.text(`Generated: ${new Date().toLocaleString()}`, 14, 46);

    // SUMMARY BOX
    doc.setFillColor(240,240,240);
    doc.rect(14, 55, 180, 25, "F");

    doc.setFontSize(12);
    doc.text("Executive Summary", 16, 63);

    doc.setFontSize(10);
    doc.text(
      `Critical: ${summary.critical}   High: ${summary.high}   Medium: ${summary.medium}   Low: ${summary.low}`,
      16,
      72
    );

    // TABLE
    const rows = scanVulns.map(v => [
      v.name,
      v.severity,
      v.cvss_score || "N/A",
      v.path,
      v.owasp_category || "-"
    ]);

    autoTable(doc, {
      startY: 90,
      head: [["Name", "Severity", "CVSS", "Target", "OWASP"]],
      body: rows,
      styles: { fontSize: 9 },
      headStyles: {
        fillColor: [37, 99, 235],
        textColor: 255
      }
    });

    let y = doc.lastAutoTable.finalY + 10;

    // RISK SECTION
    doc.setFontSize(14);
    doc.text("Risk Analysis", 14, y);

    y += 8;

    doc.setFontSize(10);
    doc.text(
      "This report highlights detected vulnerabilities using automated VAPT scanning. Immediate action is recommended for Critical and High severity issues.",
      14,
      y,
      { maxWidth: 180 }
    );

    // LOGS
    y += 20;

    doc.setFontSize(14);
    doc.text("Scan Logs (Preview)", 14, y);

    y += 8;

    doc.setFontSize(8);

    displayedLogs.slice(0, 15).forEach((log, i) => {
      doc.text(`- ${log}`, 14, y + i * 5, { maxWidth: 180 });
    });

    // FOOTER
    doc.setFontSize(9);
    doc.text(
      "Generated by AutoVAPT | Confidential Security Report",
      14,
      285
    );

    doc.save(`AutoVAPT_Report_${id}.pdf`);
  };

  // ---------------- DOWNLOAD ----------------
  const downloadPDF = () => {
    window.open(`http://localhost:8000/report/pdf/${id}`);
  };

  const downloadDOCX = () => {
    window.open(`http://localhost:8000/report/docx/${id}`);
  };

  const downloadExcel = () => {
    window.open(`http://localhost:8000/report/excel/${id}`);
  };

  // ---------------- UI ----------------
  return (
    <div style={{padding:"30px", color:"white"}}>

      <h1>📄 Scan Report #{id}</h1>

      {/* BUTTONS */}
      <div style={{marginBottom:"20px"}}>
        <button onClick={exportPDF}>Export PDF</button>

        <button onClick={downloadPDF} style={{marginLeft:"10px"}}>
          Backend PDF
        </button>

        <button onClick={downloadDOCX} style={{marginLeft:"10px"}}>
          DOCX
        </button>

        <button onClick={downloadExcel} style={{marginLeft:"10px"}}>
          Excel
        </button>
      </div>

      {/* SUMMARY */}
      <div style={{background:"#020617", padding:"20px", borderRadius:"10px"}}>
        <h2>Executive Summary</h2>
        <p>🔴 Critical: {summary.critical}</p>
        <p>🟠 High: {summary.high}</p>
        <p>🟡 Medium: {summary.medium}</p>
        <p>🟢 Low: {summary.low}</p>
      </div>

      {/* VULNS */}
      <div style={{marginTop:"20px"}}>
        <h2>Vulnerabilities</h2>

        {scanVulns.map((v,i)=>(
          <div key={i} style={{
            borderBottom:"1px solid #1e293b",
            padding:"10px"
          }}>
            <b>{v.name}</b> ({v.severity})
            <p>{v.description}</p>
          </div>
        ))}
      </div>

      {/* AI */}
      <div style={{marginTop:"20px"}}>
        <h2>AI Exploit Suggestions</h2>

        {exploits.map((e,i)=>(
          <div key={i}>
            <b>{e.name}</b>
            <p>{e.exploit}</p>
          </div>
        ))}
      </div>

      {/* LOGS */}
      <div style={{marginTop:"20px"}}>
        <h2>Scan Logs</h2>

        {displayedLogs.slice(0,20).map((log,i)=>(
          <div key={i}>{log}</div>
        ))}
      </div>

    </div>
  );
}

export default ScanReport; 